spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:testdb/schema-h2.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/undefined
    username: sa
    password:

  jpa:
    database: h2




